version: "3"
services:
  api:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app
    environment:
      - DATABASE_HOSTNAME=localhost
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=louis.debouzy
      - DATABASE_NAME=postgre
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=6610374e18099ce7424c934b3f36db7bcb12389a6ccafc53b2d24533c5a4a9cc
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=louis.debouzy
      - POSTGRES_DB=postgre
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
